f = open("droptables.txt", "r")
tables = f.read()
f.close()

tables = tables.replace("<tr>", " ")
tables = tables.replace("</tr>", " ")
tables = tables.replace("<td>", " ")
tables = tables.replace("</td>", " ")
tables = tables.replace("\\r", " ")
tables = tables.replace("\\n", " ")
tables = tables.replace("<br/>", " ")
tables = tables.replace("<p>", " ")
tables = tables.replace("<a", " ")
tables = tables.replace("</a>", " ")
tables = tables.replace("<li>", " ")
tables = tables.replace("</li>", " ")

f = open("droptables.txt", "w")
f.write(tables)
f.close()
